on:
  issues:
    types: [opened]

jobs:
  MyStats:
    runs-on: ubuntu-latest
    if: startsWith(github.event.issue.title, 'MyStats')
    steps:
      - uses: actions/checkout@v2
      - name: collect stats
        uses: ./myStats
        id: stats
        with:
          user: ${{ github.event.issue.user.login }}
          userID: ${{ github.event.issue.user.id }}
      - name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: ${{ steps.stats.outputs.closeIssueMsg }}